# For now just a simple squeleton needs proper setting for deployment to ui test env
parameters:
- name: environment
  type: string
  default: ''
- name: basicAuthentication
  type: string
  default: ''


stages:
  - stage: OMLUpdate
    jobs:
      - job: oml_update
        displayName: 'Update OML in environment ${{ parameters.environment }}'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: 'npm-steps.yml'
            parameters:
              workingDirectory: 'CI/templates'
          - script: 'npm start --authentication="${{ parameters.basicAuthentication }}" --environment=${{ parameters.environment }} --repositoryURL="$(Build.Repository.Uri)" --branch=$(Build.SourceBranchName)'
            workingDirectory: 'CI/templates'
